### PR TITLE
Added Unity Deployment Tools

### LINKED ISSUE #42: Automated deployment
While this wouldn't actually buld per se (though if it is actually possible distributing a dll is way better than a unity package with source code) some sort of continuous integration or at least automated deployment would be a huge help. (it would also help with the future docs)

### PR DESCRIPTION
**Pull request by dh-nunes**
See discussion at ricardojmendez/UnitySteerExamples#6. Fixes #42.

Example [pre-release](https://github.com/GandaG/UnitySteer/releases/tag/v3.1.1-alpha-11) and [github pages](https://gandag.github.io/UnitySteer/). [Build history](https://travis-ci.org/GandaG/UnitySteer/builds) in travis.

### CODE REVIEW

**Comment by ricardojmendez** [comment]
Merged, thanks @GandaG!  I'll probably retain the same version number, seeing as this only adds the deploy folder and has no direct effect on UnitySteer itself.

Cheers!

**Comment by dh-nunes** [comment]
Sure :p I may have forgotten to say it only deploys with a tag, if not on a pr and if you have a github access token in your repository settings in travis. 

Don't forget to update the badge in the readme to point to your repo in travis (it's currenty still aimed at mine :) ) an to enable the repo in travis (or it won't build at all).

As a final note, I'd appreciate if you could add my repo to the dependencies (or wherever you think best) so it gets a little more exposure :p

**Comment by ricardojmendez** [comment]
Just about to do that. Is https://github.com/GandaG/UnitySteer/releases/ where you plan to maintain these?

**Comment by dh-nunes** [comment]
> Is https://github.com/GandaG/UnitySteer/releases/ where you plan to maintain these?

I don't understand what you mean... Those tags (and releases) were just for me to check if everything was building  correctly. Some of them don't even work I believe. Once you push a tag (and if you fulfill the other requirements) it will deploy to your releases in your repo.

**Comment by dh-nunes** [comment]
[UDT 1.1.3](https://github.com/GandaG/unity-deploy-tools/releases/tag/v1.1.3) now deploys as .unitypackage instead of zip.

**Pull request merged**
