### PR TITLE
Custom Forward/Up vectors, specify allowed rotation axes

### PR DESCRIPTION
**Pull request by rattuscz**
So this allowes me to setup 2D project with forward as Vector3.up and up vector as Vector3.back
With only Z axis allowed for rotation it correctly rotates the sprites.

Without changing these, the behavior should be the same as before changes - just Slerp is done on Quaternion not on the direction vector.

One major thing to still do is have the Up/Forward vectors as global options. Now it's needed to be set on each DetectableObject separately.. ( managable by prefabs I guess )

### CODE REVIEW

**Comment by LordSharpe** [comment]
I've tested this on my 2D project, works well.

**Comment by ricardojmendez** [comment]
Thanks for confirming @LordSharpe. I haven't had a breather to test and integrate myself, but having external confirmation helps assure others who may want to try it.

Cheers!

**Comment by pjohalloran** [comment]
Are you planning on merging this in? Looks useful for 2D work.

**Comment by ricardojmendez** [comment]
Closing, as I've merged #39 which has a different 2D support implementation on independent behaviors.

**Pull request closed without merging**
